/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.java_avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Stock_Symbol extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1096706271347660941L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Stock_Symbol\",\"namespace\":\"org.example.java_avro.schema\",\"fields\":[{\"name\":\"symbol\",\"type\":\"string\"},{\"name\":\"price\",\"type\":[\"long\",\"null\"]},{\"name\":\"company\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Stock_Symbol> ENCODER =
      new BinaryMessageEncoder<Stock_Symbol>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Stock_Symbol> DECODER =
      new BinaryMessageDecoder<Stock_Symbol>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Stock_Symbol> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Stock_Symbol> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Stock_Symbol>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Stock_Symbol to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Stock_Symbol from a ByteBuffer. */
  public static Stock_Symbol fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence symbol;
  @Deprecated public java.lang.Long price;
  @Deprecated public java.lang.CharSequence company;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Stock_Symbol() {}

  /**
   * All-args constructor.
   * @param symbol The new value for symbol
   * @param price The new value for price
   * @param company The new value for company
   */
  public Stock_Symbol(java.lang.CharSequence symbol, java.lang.Long price, java.lang.CharSequence company) {
    this.symbol = symbol;
    this.price = price;
    this.company = company;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return symbol;
    case 1: return price;
    case 2: return company;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: symbol = (java.lang.CharSequence)value$; break;
    case 1: price = (java.lang.Long)value$; break;
    case 2: company = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'symbol' field.
   * @return The value of the 'symbol' field.
   */
  public java.lang.CharSequence getSymbol() {
    return symbol;
  }

  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(java.lang.CharSequence value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public java.lang.Long getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Long value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'company' field.
   * @return The value of the 'company' field.
   */
  public java.lang.CharSequence getCompany() {
    return company;
  }

  /**
   * Sets the value of the 'company' field.
   * @param value the value to set.
   */
  public void setCompany(java.lang.CharSequence value) {
    this.company = value;
  }

  /**
   * Creates a new Stock_Symbol RecordBuilder.
   * @return A new Stock_Symbol RecordBuilder
   */
  public static org.example.java_avro.schema.Stock_Symbol.Builder newBuilder() {
    return new org.example.java_avro.schema.Stock_Symbol.Builder();
  }

  /**
   * Creates a new Stock_Symbol RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Stock_Symbol RecordBuilder
   */
  public static org.example.java_avro.schema.Stock_Symbol.Builder newBuilder(org.example.java_avro.schema.Stock_Symbol.Builder other) {
    return new org.example.java_avro.schema.Stock_Symbol.Builder(other);
  }

  /**
   * Creates a new Stock_Symbol RecordBuilder by copying an existing Stock_Symbol instance.
   * @param other The existing instance to copy.
   * @return A new Stock_Symbol RecordBuilder
   */
  public static org.example.java_avro.schema.Stock_Symbol.Builder newBuilder(org.example.java_avro.schema.Stock_Symbol other) {
    return new org.example.java_avro.schema.Stock_Symbol.Builder(other);
  }

  /**
   * RecordBuilder for Stock_Symbol instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Stock_Symbol>
    implements org.apache.avro.data.RecordBuilder<Stock_Symbol> {

    private java.lang.CharSequence symbol;
    private java.lang.Long price;
    private java.lang.CharSequence company;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.java_avro.schema.Stock_Symbol.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.price)) {
        this.price = data().deepCopy(fields()[1].schema(), other.price);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.company)) {
        this.company = data().deepCopy(fields()[2].schema(), other.company);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Stock_Symbol instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.java_avro.schema.Stock_Symbol other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.symbol)) {
        this.symbol = data().deepCopy(fields()[0].schema(), other.symbol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.price)) {
        this.price = data().deepCopy(fields()[1].schema(), other.price);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.company)) {
        this.company = data().deepCopy(fields()[2].schema(), other.company);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'symbol' field.
      * @return The value.
      */
    public java.lang.CharSequence getSymbol() {
      return symbol;
    }

    /**
      * Sets the value of the 'symbol' field.
      * @param value The value of 'symbol'.
      * @return This builder.
      */
    public org.example.java_avro.schema.Stock_Symbol.Builder setSymbol(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.symbol = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'symbol' field has been set.
      * @return True if the 'symbol' field has been set, false otherwise.
      */
    public boolean hasSymbol() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'symbol' field.
      * @return This builder.
      */
    public org.example.java_avro.schema.Stock_Symbol.Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public java.lang.Long getPrice() {
      return price;
    }

    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public org.example.java_avro.schema.Stock_Symbol.Builder setPrice(java.lang.Long value) {
      validate(fields()[1], value);
      this.price = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public org.example.java_avro.schema.Stock_Symbol.Builder clearPrice() {
      price = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'company' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompany() {
      return company;
    }

    /**
      * Sets the value of the 'company' field.
      * @param value The value of 'company'.
      * @return This builder.
      */
    public org.example.java_avro.schema.Stock_Symbol.Builder setCompany(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.company = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'company' field has been set.
      * @return True if the 'company' field has been set, false otherwise.
      */
    public boolean hasCompany() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'company' field.
      * @return This builder.
      */
    public org.example.java_avro.schema.Stock_Symbol.Builder clearCompany() {
      company = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Stock_Symbol build() {
      try {
        Stock_Symbol record = new Stock_Symbol();
        record.symbol = fieldSetFlags()[0] ? this.symbol : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.price = fieldSetFlags()[1] ? this.price : (java.lang.Long) defaultValue(fields()[1]);
        record.company = fieldSetFlags()[2] ? this.company : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Stock_Symbol>
    WRITER$ = (org.apache.avro.io.DatumWriter<Stock_Symbol>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Stock_Symbol>
    READER$ = (org.apache.avro.io.DatumReader<Stock_Symbol>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
